/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author user
 */
public class quest01 extends javax.swing.JPanel {

    /**
     * Creates new form quest01
     */
    public quest01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p1_button_dOption = new javax.swing.JRadioButton();
        p1_btn_volver = new javax.swing.JButton();
        p1_button_bOption = new javax.swing.JRadioButton();
        p1_button_aOption = new javax.swing.JRadioButton();
        p1_btn_avanzar = new javax.swing.JButton();
        p1_button_cOption = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        p1_button_dOption.setText("d) Los conductores están obligados a su obediencia, aun cuando la Policía Nacional del Perú asignada al tránsito  pueda indicar lo contrario. ");

        p1_btn_volver.setText("jButton1");

        p1_button_bOption.setText("b) Los conductores y los peatones están obligados a su obediencia, salvo instrucción de la Policía Nacional del Perú  asignada al tránsito que indique lo contrario.");

        p1_button_aOption.setText("a) Solo los peatones están obligados a su obediencia.");
        p1_button_aOption.setBorder(null);

        p1_btn_avanzar.setText("jButton2");

        p1_button_cOption.setText("c) Solo los conductores están obligados a su obediencia. ");

        jLabel6.setText("1.- Respecto de los dispositivos de control o regulación del tránsito:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1_button_aOption)
                        .addComponent(p1_button_bOption)
                        .addComponent(p1_button_cOption)
                        .addComponent(p1_button_dOption)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(p1_btn_volver)
                            .addGap(41, 41, 41)
                            .addComponent(p1_btn_avanzar)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)
                    .addComponent(p1_button_aOption)
                    .addGap(18, 18, 18)
                    .addComponent(p1_button_bOption)
                    .addGap(18, 18, 18)
                    .addComponent(p1_button_cOption)
                    .addGap(12, 12, 12)
                    .addComponent(p1_button_dOption)
                    .addGap(74, 74, 74)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p1_btn_volver)
                        .addComponent(p1_btn_avanzar))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton p1_btn_avanzar;
    private javax.swing.JButton p1_btn_volver;
    private javax.swing.JRadioButton p1_button_aOption;
    private javax.swing.JRadioButton p1_button_bOption;
    private javax.swing.JRadioButton p1_button_cOption;
    private javax.swing.JRadioButton p1_button_dOption;
    // End of variables declaration//GEN-END:variables
}
